### ISSUE TITLE
problem infering zend tags

### ISSUE THREAD

**Issue by bendavies** [pyrech/composer-changelogs#26] opened 2016-02-19 14:36 UTC
This plugin will report a URL like this:

https://github.com/zendframework/zend-eventmanager/compare/3.0.0...3.0.1
where as the correct tags are:
https://github.com/zendframework/zend-eventmanager/compare/release-3.0.0...release-3.0.1

**Comment by pyrech** [comment] 2016-02-21 14:59
Hi. Thanks for reporting the issue. I will try to give it a look soon.

**Comment by pyrech** [comment] 2016-02-27 21:53
After some investigation, I think the problem is located in Composer [itself](https://github.com/composer/composer/blob/7ac783197bcae20cf73bc016e8fdeaf793daeae2/src/Composer/Repository/VcsRepository.php#L143-L144). Composer removes the `release-` prefix and after debugging the information I have access from the plugin, I'm afraid of not being able to fix this issue on my side...

**Comment by BigMichi1** [comment] 2018-12-12 08:15
is it maybe possible to add some extra configuration map inside composer.json like commit configuration?

e.g.
```
"extra": {
    "composer-changelogs": {
        "prefixes": {
            "zendframework/*": "release-",
            "zendframework/zend-view": "foo_",
        }
    }
}

**Comment by pyrech** [comment] 2018-12-12 08:38
Hi :)

Yes, that could be an option. Not ideal as it needs to be done per project but better than nothing. Would you mind to give it a try?

**Comment by BigMichi1** [comment] 2019-01-07 08:51
will try my best

**Comment by lyrixx** [comment] 2022-05-04 14:57
Hello, is it still relevant? Or could we close this issue?

**Comment by pyrech** [comment] 2023-02-04 16:23
Let's close this issue for inactivity. Do not hesitate to reopen if this is still relevant. Thanks :)

**Closed by pyrech** 2023-02-04 16:23 UTC
Labels: bug, wontfix
